// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"nichebox/service/user/rpc/internal/logic"
	"nichebox/service/user/rpc/internal/svc"
	"nichebox/service/user/rpc/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) CheckEmail(ctx context.Context, in *user.CheckEmailRequest) (*user.CheckEmailResponse, error) {
	l := logic.NewCheckEmailLogic(ctx, s.svcCtx)
	return l.CheckEmail(in)
}

func (s *UserServer) GetUidByEmailAndPwd(ctx context.Context, in *user.GetUidByEmailAndPwdRequest) (*user.GetUidByEmailAndPwdResponse, error) {
	l := logic.NewGetUidByEmailAndPwdLogic(ctx, s.svcCtx)
	return l.GetUidByEmailAndPwd(in)
}

func (s *UserServer) CheckUid(ctx context.Context, in *user.CheckUidRequest) (*user.CheckUidResponse, error) {
	l := logic.NewCheckUidLogic(ctx, s.svcCtx)
	return l.CheckUid(in)
}

func (s *UserServer) SetVerificationCode(ctx context.Context, in *user.SetVerificationCodeRequest) (*user.SetVerificationCodeResponse, error) {
	l := logic.NewSetVerificationCodeLogic(ctx, s.svcCtx)
	return l.SetVerificationCode(in)
}

func (s *UserServer) GetVerificationCode(ctx context.Context, in *user.GetVerificationCodeRequest) (*user.GetVerificationCodeResponse, error) {
	l := logic.NewGetVerificationCodeLogic(ctx, s.svcCtx)
	return l.GetVerificationCode(in)
}
