// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"nichebox/service/user/rpc/internal/logic"
	"nichebox/service/user/rpc/internal/svc"
	"nichebox/service/user/rpc/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) CheckEmail(ctx context.Context, in *user.CheckEmailRequest) (*user.CheckEmailResponse, error) {
	l := logic.NewCheckEmailLogic(ctx, s.svcCtx)
	return l.CheckEmail(in)
}

func (s *UserServer) GetUserInfoByEmail(ctx context.Context, in *user.GetUserInfoByEmailRequest) (*user.GetUserInfoByEmailResponse, error) {
	l := logic.NewGetUserInfoByEmailLogic(ctx, s.svcCtx)
	return l.GetUserInfoByEmail(in)
}
