// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"nichebox/service/relation/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getfollowercount",
				Handler: GetFollowerCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getfollowers",
				Handler: GetFollowersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getfollowingcount",
				Handler: GetFollowingCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getfollowings",
				Handler: GetFollowingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unfollow",
				Handler: UnfollowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/relation"),
	)
}
