// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: like.proto

package like

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Like_ThumbsUp_FullMethodName        = "/likeclient.Like/ThumbsUp"
	Like_CancelThumbsUp_FullMethodName  = "/likeclient.Like/CancelThumbsUp"
	Like_ThumbsUpCount_FullMethodName   = "/likeclient.Like/ThumbsUpCount"
	Like_ThumbsUpHistory_FullMethodName = "/likeclient.Like/ThumbsUpHistory"
)

// LikeClient is the client API for Like service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeClient interface {
	ThumbsUp(ctx context.Context, in *ThumbsUpRequest, opts ...grpc.CallOption) (*ThumbsUpResponse, error)
	CancelThumbsUp(ctx context.Context, in *CancelThumbsUpRequest, opts ...grpc.CallOption) (*CancelThumbsResponse, error)
	ThumbsUpCount(ctx context.Context, in *ThumbsUpCountRequest, opts ...grpc.CallOption) (*ThumbsUpCountResponse, error)
	ThumbsUpHistory(ctx context.Context, in *ThumbsUpHistoryRequest, opts ...grpc.CallOption) (*ThumbsUpHistoryResponse, error)
}

type likeClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeClient(cc grpc.ClientConnInterface) LikeClient {
	return &likeClient{cc}
}

func (c *likeClient) ThumbsUp(ctx context.Context, in *ThumbsUpRequest, opts ...grpc.CallOption) (*ThumbsUpResponse, error) {
	out := new(ThumbsUpResponse)
	err := c.cc.Invoke(ctx, Like_ThumbsUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) CancelThumbsUp(ctx context.Context, in *CancelThumbsUpRequest, opts ...grpc.CallOption) (*CancelThumbsResponse, error) {
	out := new(CancelThumbsResponse)
	err := c.cc.Invoke(ctx, Like_CancelThumbsUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) ThumbsUpCount(ctx context.Context, in *ThumbsUpCountRequest, opts ...grpc.CallOption) (*ThumbsUpCountResponse, error) {
	out := new(ThumbsUpCountResponse)
	err := c.cc.Invoke(ctx, Like_ThumbsUpCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) ThumbsUpHistory(ctx context.Context, in *ThumbsUpHistoryRequest, opts ...grpc.CallOption) (*ThumbsUpHistoryResponse, error) {
	out := new(ThumbsUpHistoryResponse)
	err := c.cc.Invoke(ctx, Like_ThumbsUpHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServer is the server API for Like service.
// All implementations must embed UnimplementedLikeServer
// for forward compatibility
type LikeServer interface {
	ThumbsUp(context.Context, *ThumbsUpRequest) (*ThumbsUpResponse, error)
	CancelThumbsUp(context.Context, *CancelThumbsUpRequest) (*CancelThumbsResponse, error)
	ThumbsUpCount(context.Context, *ThumbsUpCountRequest) (*ThumbsUpCountResponse, error)
	ThumbsUpHistory(context.Context, *ThumbsUpHistoryRequest) (*ThumbsUpHistoryResponse, error)
	mustEmbedUnimplementedLikeServer()
}

// UnimplementedLikeServer must be embedded to have forward compatible implementations.
type UnimplementedLikeServer struct {
}

func (UnimplementedLikeServer) ThumbsUp(context.Context, *ThumbsUpRequest) (*ThumbsUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThumbsUp not implemented")
}
func (UnimplementedLikeServer) CancelThumbsUp(context.Context, *CancelThumbsUpRequest) (*CancelThumbsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelThumbsUp not implemented")
}
func (UnimplementedLikeServer) ThumbsUpCount(context.Context, *ThumbsUpCountRequest) (*ThumbsUpCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThumbsUpCount not implemented")
}
func (UnimplementedLikeServer) ThumbsUpHistory(context.Context, *ThumbsUpHistoryRequest) (*ThumbsUpHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThumbsUpHistory not implemented")
}
func (UnimplementedLikeServer) mustEmbedUnimplementedLikeServer() {}

// UnsafeLikeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServer will
// result in compilation errors.
type UnsafeLikeServer interface {
	mustEmbedUnimplementedLikeServer()
}

func RegisterLikeServer(s grpc.ServiceRegistrar, srv LikeServer) {
	s.RegisterService(&Like_ServiceDesc, srv)
}

func _Like_ThumbsUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbsUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).ThumbsUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_ThumbsUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).ThumbsUp(ctx, req.(*ThumbsUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_CancelThumbsUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelThumbsUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).CancelThumbsUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_CancelThumbsUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).CancelThumbsUp(ctx, req.(*CancelThumbsUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_ThumbsUpCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbsUpCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).ThumbsUpCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_ThumbsUpCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).ThumbsUpCount(ctx, req.(*ThumbsUpCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_ThumbsUpHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbsUpHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).ThumbsUpHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_ThumbsUpHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).ThumbsUpHistory(ctx, req.(*ThumbsUpHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Like_ServiceDesc is the grpc.ServiceDesc for Like service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Like_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "likeclient.Like",
	HandlerType: (*LikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ThumbsUp",
			Handler:    _Like_ThumbsUp_Handler,
		},
		{
			MethodName: "CancelThumbsUp",
			Handler:    _Like_CancelThumbsUp_Handler,
		},
		{
			MethodName: "ThumbsUpCount",
			Handler:    _Like_ThumbsUpCount_Handler,
		},
		{
			MethodName: "ThumbsUpHistory",
			Handler:    _Like_ThumbsUpHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "like.proto",
}
