// Code generated by goctl. DO NOT EDIT.
package types

type HandShakeRequest struct {
	UserAgent     string `header:"User-Agent"`
	RemoteAddress string `header:"Remote-Address"`
}

type HandShakeResponse struct {
	Token string `json:"token"`
}
