// Code generated by goctl. DO NOT EDIT.
package types

type CreateBoxRequest struct {
	Name         string `json:"name"`
	Introduction string `json:"introduction"`
}

type CreateBoxResponse struct {
	BoxId string `json:"box_id"`
}

type UpdateBoxInfoRequest struct {
	BoxId        string `json:"box_id"`
	Name         string `json:"name"`
	Introduction string `json:"introduction"`
}

type UpdateBoxInfoResponse struct {
}

type GetBoxInfoRequest struct {
	BoxId string `json:"box_id"`
}

type GetBoxInfoResponse struct {
	Name         string `json:"name"`
	Introduction string `json:"introduction"`
}
