// Code generated by goctl. DO NOT EDIT.
// Source: longConn.proto

package server

import (
	"context"

	"nichebox/service/long-connection/rpc/internal/logic"
	"nichebox/service/long-connection/rpc/internal/svc"
	"nichebox/service/long-connection/rpc/pb/longConn"
)

type LongConnServer struct {
	svcCtx *svc.ServiceContext
	longConn.UnimplementedLongConnServer
}

func NewLongConnServer(svcCtx *svc.ServiceContext) *LongConnServer {
	return &LongConnServer{
		svcCtx: svcCtx,
	}
}

func (s *LongConnServer) HandShake(ctx context.Context, in *longConn.HandShakeRequest) (*longConn.HandShakeResponse, error) {
	l := logic.NewHandShakeLogic(ctx, s.svcCtx)
	return l.HandShake(in)
}
