// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: box_user.proto

package boxuser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BoxUser_AddOwner_FullMethodName       = "/boxuserclient.BoxUser/AddOwner"
	BoxUser_AddOwnerRevert_FullMethodName = "/boxuserclient.BoxUser/AddOwnerRevert"
	BoxUser_AddBoxUser_FullMethodName     = "/boxuserclient.BoxUser/AddBoxUser"
	BoxUser_RemoveBoxUser_FullMethodName  = "/boxuserclient.BoxUser/RemoveBoxUser"
	BoxUser_SetRole_FullMethodName        = "/boxuserclient.BoxUser/SetRole"
	BoxUser_GetRole_FullMethodName        = "/boxuserclient.BoxUser/GetRole"
)

// BoxUserClient is the client API for BoxUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxUserClient interface {
	AddOwner(ctx context.Context, in *AddOwnerRequest, opts ...grpc.CallOption) (*AddOwnerRequest, error)
	AddOwnerRevert(ctx context.Context, in *AddOwnerRequest, opts ...grpc.CallOption) (*AddOwnerRequest, error)
	AddBoxUser(ctx context.Context, in *AddBoxUserRequest, opts ...grpc.CallOption) (*AddBoxUserResponse, error)
	RemoveBoxUser(ctx context.Context, in *RemoveBoxUserRequest, opts ...grpc.CallOption) (*RemoveBoxUserResponse, error)
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error)
	GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
}

type boxUserClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxUserClient(cc grpc.ClientConnInterface) BoxUserClient {
	return &boxUserClient{cc}
}

func (c *boxUserClient) AddOwner(ctx context.Context, in *AddOwnerRequest, opts ...grpc.CallOption) (*AddOwnerRequest, error) {
	out := new(AddOwnerRequest)
	err := c.cc.Invoke(ctx, BoxUser_AddOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxUserClient) AddOwnerRevert(ctx context.Context, in *AddOwnerRequest, opts ...grpc.CallOption) (*AddOwnerRequest, error) {
	out := new(AddOwnerRequest)
	err := c.cc.Invoke(ctx, BoxUser_AddOwnerRevert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxUserClient) AddBoxUser(ctx context.Context, in *AddBoxUserRequest, opts ...grpc.CallOption) (*AddBoxUserResponse, error) {
	out := new(AddBoxUserResponse)
	err := c.cc.Invoke(ctx, BoxUser_AddBoxUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxUserClient) RemoveBoxUser(ctx context.Context, in *RemoveBoxUserRequest, opts ...grpc.CallOption) (*RemoveBoxUserResponse, error) {
	out := new(RemoveBoxUserResponse)
	err := c.cc.Invoke(ctx, BoxUser_RemoveBoxUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxUserClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error) {
	out := new(SetRoleResponse)
	err := c.cc.Invoke(ctx, BoxUser_SetRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxUserClient) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	out := new(GetRoleResponse)
	err := c.cc.Invoke(ctx, BoxUser_GetRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxUserServer is the server API for BoxUser service.
// All implementations must embed UnimplementedBoxUserServer
// for forward compatibility
type BoxUserServer interface {
	AddOwner(context.Context, *AddOwnerRequest) (*AddOwnerRequest, error)
	AddOwnerRevert(context.Context, *AddOwnerRequest) (*AddOwnerRequest, error)
	AddBoxUser(context.Context, *AddBoxUserRequest) (*AddBoxUserResponse, error)
	RemoveBoxUser(context.Context, *RemoveBoxUserRequest) (*RemoveBoxUserResponse, error)
	SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error)
	GetRole(context.Context, *GetRoleRequest) (*GetRoleResponse, error)
	mustEmbedUnimplementedBoxUserServer()
}

// UnimplementedBoxUserServer must be embedded to have forward compatible implementations.
type UnimplementedBoxUserServer struct {
}

func (UnimplementedBoxUserServer) AddOwner(context.Context, *AddOwnerRequest) (*AddOwnerRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOwner not implemented")
}
func (UnimplementedBoxUserServer) AddOwnerRevert(context.Context, *AddOwnerRequest) (*AddOwnerRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOwnerRevert not implemented")
}
func (UnimplementedBoxUserServer) AddBoxUser(context.Context, *AddBoxUserRequest) (*AddBoxUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBoxUser not implemented")
}
func (UnimplementedBoxUserServer) RemoveBoxUser(context.Context, *RemoveBoxUserRequest) (*RemoveBoxUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBoxUser not implemented")
}
func (UnimplementedBoxUserServer) SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedBoxUserServer) GetRole(context.Context, *GetRoleRequest) (*GetRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedBoxUserServer) mustEmbedUnimplementedBoxUserServer() {}

// UnsafeBoxUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxUserServer will
// result in compilation errors.
type UnsafeBoxUserServer interface {
	mustEmbedUnimplementedBoxUserServer()
}

func RegisterBoxUserServer(s grpc.ServiceRegistrar, srv BoxUserServer) {
	s.RegisterService(&BoxUser_ServiceDesc, srv)
}

func _BoxUser_AddOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxUserServer).AddOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxUser_AddOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxUserServer).AddOwner(ctx, req.(*AddOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxUser_AddOwnerRevert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxUserServer).AddOwnerRevert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxUser_AddOwnerRevert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxUserServer).AddOwnerRevert(ctx, req.(*AddOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxUser_AddBoxUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBoxUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxUserServer).AddBoxUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxUser_AddBoxUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxUserServer).AddBoxUser(ctx, req.(*AddBoxUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxUser_RemoveBoxUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBoxUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxUserServer).RemoveBoxUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxUser_RemoveBoxUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxUserServer).RemoveBoxUser(ctx, req.(*RemoveBoxUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxUser_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxUserServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxUser_SetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxUserServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxUser_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxUserServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxUser_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxUserServer).GetRole(ctx, req.(*GetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoxUser_ServiceDesc is the grpc.ServiceDesc for BoxUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boxuserclient.BoxUser",
	HandlerType: (*BoxUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOwner",
			Handler:    _BoxUser_AddOwner_Handler,
		},
		{
			MethodName: "AddOwnerRevert",
			Handler:    _BoxUser_AddOwnerRevert_Handler,
		},
		{
			MethodName: "AddBoxUser",
			Handler:    _BoxUser_AddBoxUser_Handler,
		},
		{
			MethodName: "RemoveBoxUser",
			Handler:    _BoxUser_RemoveBoxUser_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _BoxUser_SetRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _BoxUser_GetRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "box_user.proto",
}
