// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.1
// source: box_user.proto

package boxuser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_Owner         UserRole = 0
	UserRole_Administrator UserRole = 1
	UserRole_Member        UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "Owner",
		1: "Administrator",
		2: "Member",
	}
	UserRole_value = map[string]int32{
		"Owner":         0,
		"Administrator": 1,
		"Member":        2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_box_user_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_box_user_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_box_user_proto_rawDescGZIP(), []int{0}
}

// AddUser
type AddOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Bid int64 `protobuf:"varint,2,opt,name=Bid,proto3" json:"Bid,omitempty"`
}

func (x *AddOwnerRequest) Reset() {
	*x = AddOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOwnerRequest) ProtoMessage() {}

func (x *AddOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOwnerRequest.ProtoReflect.Descriptor instead.
func (*AddOwnerRequest) Descriptor() ([]byte, []int) {
	return file_box_user_proto_rawDescGZIP(), []int{0}
}

func (x *AddOwnerRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddOwnerRequest) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

type AddOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddOwnerResponse) Reset() {
	*x = AddOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOwnerResponse) ProtoMessage() {}

func (x *AddOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOwnerResponse.ProtoReflect.Descriptor instead.
func (*AddOwnerResponse) Descriptor() ([]byte, []int) {
	return file_box_user_proto_rawDescGZIP(), []int{1}
}

var File_box_user_proto protoreflect.FileDescriptor

var file_box_user_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x6f, 0x78, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x62, 0x6f, 0x78, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22,
	0x35, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x55, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x42, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x34, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x02,
	0x32, 0xa7, 0x01, 0x0a, 0x07, 0x42, 0x6f, 0x78, 0x55, 0x73, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x62, 0x6f, 0x78, 0x75, 0x73,
	0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x6f, 0x78, 0x75, 0x73,
	0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x12, 0x1e, 0x2e, 0x62, 0x6f, 0x78,
	0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x6f, 0x78,
	0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f,
	0x62, 0x6f, 0x78, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_box_user_proto_rawDescOnce sync.Once
	file_box_user_proto_rawDescData = file_box_user_proto_rawDesc
)

func file_box_user_proto_rawDescGZIP() []byte {
	file_box_user_proto_rawDescOnce.Do(func() {
		file_box_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_box_user_proto_rawDescData)
	})
	return file_box_user_proto_rawDescData
}

var file_box_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_box_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_box_user_proto_goTypes = []interface{}{
	(UserRole)(0),            // 0: boxuserclient.UserRole
	(*AddOwnerRequest)(nil),  // 1: boxuserclient.AddOwnerRequest
	(*AddOwnerResponse)(nil), // 2: boxuserclient.AddOwnerResponse
}
var file_box_user_proto_depIdxs = []int32{
	1, // 0: boxuserclient.BoxUser.AddOwner:input_type -> boxuserclient.AddOwnerRequest
	1, // 1: boxuserclient.BoxUser.AddOwnerRevert:input_type -> boxuserclient.AddOwnerRequest
	1, // 2: boxuserclient.BoxUser.AddOwner:output_type -> boxuserclient.AddOwnerRequest
	1, // 3: boxuserclient.BoxUser.AddOwnerRevert:output_type -> boxuserclient.AddOwnerRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_box_user_proto_init() }
func file_box_user_proto_init() {
	if File_box_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_box_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_box_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_box_user_proto_goTypes,
		DependencyIndexes: file_box_user_proto_depIdxs,
		EnumInfos:         file_box_user_proto_enumTypes,
		MessageInfos:      file_box_user_proto_msgTypes,
	}.Build()
	File_box_user_proto = out.File
	file_box_user_proto_rawDesc = nil
	file_box_user_proto_goTypes = nil
	file_box_user_proto_depIdxs = nil
}
