// Code generated by goctl. DO NOT EDIT.
package types

type CreatePostRequest struct {
	BoxID   int64    `json:"box_id,string"`
	Title   string   `json:"title"`
	Content string   `json:"content"`
	Photos  []string `json:"photos"`
	Cover   string   `json:"cover"`
}

type CreatePostResponse struct {
	PostID int64 `json:"post_id,string"`
}

type DeletePostRequest struct {
	PostID   int64  `json:"post_id,string"`
	Operator string `json:"operator"`
}

type DeletePostResponse struct {
}

type GetPostDetailRequest struct {
	PostID int64 `json:"post_id,string"`
}

type GetPostDetailResponse struct {
	AuthorID   int64    `json:"author_id,string"`
	AuthorName string   `json:"author_name"`
	BoxID      int64    `json:"box_id,string"`
	BoxName    string   `json:"box_name"`
	Title      string   `json:"title"`
	Content    string   `json:"content"`
	Photos     []string `json:"photos"`
	UserView   int      `json:"user_view"`
}

type IncreaseUserViewRequest struct {
	PostID int64 `json:"post_id,string"`
	Uid    int64 `json:"uid,string"`
}

type IncreaseUserViewResponse struct {
}
