// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"nichebox/service/email/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/email/sendverificationcodepwd",
				Handler: SendVerificationCodePWDHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/email/sendverificationcoderegister",
				Handler: SendVerificationCodeRegisterHandler(serverCtx),
			},
		},
		rest.WithTimeout(5000*time.Millisecond),
	)
}
