// Code generated by goctl. DO NOT EDIT.
// Source: email.proto

package server

import (
	"context"

	"nichebox/service/email/rpc/internal/logic"
	"nichebox/service/email/rpc/internal/svc"
	"nichebox/service/email/rpc/pb/email"
)

type EmailServer struct {
	svcCtx *svc.ServiceContext
	email.UnimplementedEmailServer
}

func NewEmailServer(svcCtx *svc.ServiceContext) *EmailServer {
	return &EmailServer{
		svcCtx: svcCtx,
	}
}

func (s *EmailServer) SendEmail(ctx context.Context, in *email.SendEmailRequest) (*email.SendEmailResponse, error) {
	l := logic.NewSendEmailLogic(ctx, s.svcCtx)
	return l.SendEmail(in)
}
