// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type RegisterResponse struct {
	LoginSuccess bool   `json:"login_success"`
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type CheckEmailExistsReqeust struct {
	Email string `json:"email"`
}

type CheckEmailExistsResponse struct {
	Exist bool `json:"exist"`
}

type LoginReqeust struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenReqeust struct {
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type SetUserBaseInfoRequest struct {
	Username     string `json:"username"`
	Introduction string `json:"introduction"`
}

type SetUserBaseInfoResponse struct {
}

type GetMyBaseInfoRequest struct {
}

type GetMyBaseInfoResponse struct {
	Uid          string `json:"uid"`
	UserName     string `json:"username"`
	Introduction string `json:"introduction"`
}
