// Code generated by goctl. DO NOT EDIT.
package types

type GetPostListRequest struct {
	BoxID int64  `json:"box_id,string"`
	Page  int    `json:"page"`
	Size  int    `json:"size"`
	Order string `json:"order"`
}

type GetPostListResponse struct {
	IDs []int64 `json:"ids,[]string"`
}
