// Code generated by goctl. DO NOT EDIT.
// Source: email.proto

package emailclient

import (
	"context"

	"nichebox/service/email/rpc/pb/email"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendEmailRequest  = email.SendEmailRequest
	SendEmailResponse = email.SendEmailResponse

	Email interface {
		SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	}

	defaultEmail struct {
		cli zrpc.Client
	}
)

func NewEmail(cli zrpc.Client) Email {
	return &defaultEmail{
		cli: cli,
	}
}

func (m *defaultEmail) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	client := email.NewEmailClient(m.cli.Conn())
	return client.SendEmail(ctx, in, opts...)
}
