// Code generated by goctl. DO NOT EDIT.
// Source: email.proto

package emailclient

import (
	"context"

	"nichebox/service/email/rpc/pb/email"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendVerificationCodeRequest  = email.SendVerificationCodeRequest
	SendVerificationCodeResponse = email.SendVerificationCodeResponse

	Email interface {
		SendVerificationCode(ctx context.Context, in *SendVerificationCodeRequest, opts ...grpc.CallOption) (*SendVerificationCodeResponse, error)
	}

	defaultEmail struct {
		cli zrpc.Client
	}
)

func NewEmail(cli zrpc.Client) Email {
	return &defaultEmail{
		cli: cli,
	}
}

func (m *defaultEmail) SendVerificationCode(ctx context.Context, in *SendVerificationCodeRequest, opts ...grpc.CallOption) (*SendVerificationCodeResponse, error) {
	client := email.NewEmailClient(m.cli.Conn())
	return client.SendVerificationCode(ctx, in, opts...)
}
