// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package server

import (
	"context"

	"nichebox/service/task/rpc/internal/logic"
	"nichebox/service/task/rpc/internal/svc"
	"nichebox/service/task/rpc/pb/task"
)

type TaskServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskServer
}

func NewTaskServer(svcCtx *svc.ServiceContext) *TaskServer {
	return &TaskServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServer) CreateTask(ctx context.Context, in *task.CreateTaskRequest) (*task.CreateTaskResponse, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}
