// Code generated by goctl. DO NOT EDIT.
package types

type FollowRequest struct {
	Fid int64 `json:"fid, string"`
}

type FollowResponse struct {
}

type Follower struct {
	Fid          int64  `json:"fid, string"`
	Relationship string `json:"relationship"`
	UpdateTime   string `json:"update_time"`
}

type Following struct {
	Fid          int64  `json:"fid, string"`
	Relationship string `json:"relationship"`
	UpdateTime   string `json:"update_time"`
}

type GetFollowerCountRequest struct {
	Uid int64 `json:"uid,string"`
}

type GetFollowerCountResponse struct {
	Count int `json:"count"`
}

type GetFollowersRequest struct {
	Uid   int64  `json:"uid,string"`
	Page  int    `json:"page"`
	Size  int    `json:"size"`
	Order string `json:"order"`
}

type GetFollowersResponse struct {
	Followers []*Follower `json:"followers"`
}

type GetFollowingCountRequest struct {
	Uid int64 `json:"uid,string"`
}

type GetFollowingCountResponse struct {
	Count int `json:"count"`
}

type GetFollowingsRequest struct {
	Uid   int64  `json:"uid,string"`
	Page  int    `json:"page"`
	Size  int    `json:"size"`
	Order string `json:"order"`
}

type GetFollowingsResponse struct {
	Followings []*Following `json:"followings"`
}

type GetRelationshipRequest struct {
	Fid int64 `json:"fid,string"`
}

type GetRelationshipResponse struct {
	Relationship string `json:"relationship"`
}

type UnfollowRequest struct {
	Fid int64 `json:"fid, string"`
}

type UnfollowResponse struct {
}
