// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"nichebox/service/like/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cancelthumbsup",
				Handler: CancelThumbsUpHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/thumbsup",
				Handler: ThumbsUpHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/thumbsupcount",
				Handler: ThumbsUpCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/thumbsuphistory",
				Handler: ThumbsUpHistoryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/like"),
	)
}
