// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"nichebox/service/file/rpc/internal/logic"
	"nichebox/service/file/rpc/internal/svc"
	"nichebox/service/file/rpc/pb/file"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServer) UploadImage(stream file.File_UploadImageServer) error {
	l := logic.NewUploadImageLogic(stream.Context(), s.svcCtx)
	return l.UploadImage(stream)
}

func (s *FileServer) GetFileUrl(ctx context.Context, in *file.GetFileUrlRequest) (*file.GetFileUrlResponse, error) {
	l := logic.NewGetFileUrlLogic(ctx, s.svcCtx)
	return l.GetFileUrl(in)
}
