// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package server

import (
	"context"

	"nichebox/service/feed/rpc/internal/logic"
	"nichebox/service/feed/rpc/internal/svc"
	"nichebox/service/feed/rpc/pb/feed"
)

type FeedServer struct {
	svcCtx *svc.ServiceContext
	feed.UnimplementedFeedServer
}

func NewFeedServer(svcCtx *svc.ServiceContext) *FeedServer {
	return &FeedServer{
		svcCtx: svcCtx,
	}
}

func (s *FeedServer) Push(ctx context.Context, in *feed.PushRequest) (*feed.PushResponse, error) {
	l := logic.NewPushLogic(ctx, s.svcCtx)
	return l.Push(in)
}

func (s *FeedServer) Pull(ctx context.Context, in *feed.PullRequest) (*feed.PullResponse, error) {
	l := logic.NewPullLogic(ctx, s.svcCtx)
	return l.Pull(in)
}
