// Code generated by goctl. DO NOT EDIT.
// Source: box_info.proto

package server

import (
	"context"

	"nichebox/service/box_info/rpc/internal/logic"
	"nichebox/service/box_info/rpc/internal/svc"
	"nichebox/service/box_info/rpc/pb/boxinfo"
)

type BoxInfoServer struct {
	svcCtx *svc.ServiceContext
	boxinfo.UnimplementedBoxInfoServer
}

func NewBoxInfoServer(svcCtx *svc.ServiceContext) *BoxInfoServer {
	return &BoxInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *BoxInfoServer) CreateBid(ctx context.Context, in *boxinfo.CreateBidRequest) (*boxinfo.CreateBidResponse, error) {
	l := logic.NewCreateBidLogic(ctx, s.svcCtx)
	return l.CreateBid(in)
}

func (s *BoxInfoServer) CreateBox(ctx context.Context, in *boxinfo.CreateBoxRequest) (*boxinfo.CreateBoxResponse, error) {
	l := logic.NewCreateBoxLogic(ctx, s.svcCtx)
	return l.CreateBox(in)
}

func (s *BoxInfoServer) CreateBoxRevert(ctx context.Context, in *boxinfo.CreateBoxRequest) (*boxinfo.CreateBoxResponse, error) {
	l := logic.NewCreateBoxRevertLogic(ctx, s.svcCtx)
	return l.CreateBoxRevert(in)
}
