// Code generated by goctl. DO NOT EDIT.
// Source: box-content.proto

package boxcontent

import (
	"context"

	"nichebox/service/box-content/rpc/pb/box-content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetPostListRequest         = box_content.GetPostListRequest
	GetPostListResponse        = box_content.GetPostListResponse
	ModifiedPostInfo           = box_content.ModifiedPostInfo
	UpdateDeletedPostsRequest  = box_content.UpdateDeletedPostsRequest
	UpdateDeletedPostsResponse = box_content.UpdateDeletedPostsResponse
	UpdateNewPostsRequest      = box_content.UpdateNewPostsRequest
	UpdateNewPostsResponse     = box_content.UpdateNewPostsResponse

	BoxContent interface {
		GetPostList(ctx context.Context, in *GetPostListRequest, opts ...grpc.CallOption) (*GetPostListResponse, error)
		UpdateNewPosts(ctx context.Context, in *UpdateNewPostsRequest, opts ...grpc.CallOption) (*UpdateNewPostsResponse, error)
		UpdateDeletedPosts(ctx context.Context, in *UpdateDeletedPostsRequest, opts ...grpc.CallOption) (*UpdateDeletedPostsResponse, error)
	}

	defaultBoxContent struct {
		cli zrpc.Client
	}
)

func NewBoxContent(cli zrpc.Client) BoxContent {
	return &defaultBoxContent{
		cli: cli,
	}
}

func (m *defaultBoxContent) GetPostList(ctx context.Context, in *GetPostListRequest, opts ...grpc.CallOption) (*GetPostListResponse, error) {
	client := box_content.NewBoxContentClient(m.cli.Conn())
	return client.GetPostList(ctx, in, opts...)
}

func (m *defaultBoxContent) UpdateNewPosts(ctx context.Context, in *UpdateNewPostsRequest, opts ...grpc.CallOption) (*UpdateNewPostsResponse, error) {
	client := box_content.NewBoxContentClient(m.cli.Conn())
	return client.UpdateNewPosts(ctx, in, opts...)
}

func (m *defaultBoxContent) UpdateDeletedPosts(ctx context.Context, in *UpdateDeletedPostsRequest, opts ...grpc.CallOption) (*UpdateDeletedPostsResponse, error) {
	client := box_content.NewBoxContentClient(m.cli.Conn())
	return client.UpdateDeletedPosts(ctx, in, opts...)
}
