// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"nichebox/service/post/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/createpost",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deletepost",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getpostdetail",
				Handler: GetPostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/increaseuserview",
				Handler: IncreaseUserViewHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/post"),
	)
}
